name: Contracts CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "packages/sports-manager-contracts/**"
    branches:
      - "**"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Toolkit and Remove Lockfile
        run: |
          sudo apt-get install -y make build-essential libudev-dev
          rm yarn.lock
      - name: Install Yarn and Packages
        run: |
          npm install -g yarn
          yarn install
      - name: Build Monorepo
        run: yarn build:ci
      - name: Run Contract Tests
        run: yarn contracts test
      - name: Run Contract Coverage
        run: yarn contracts coverage
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
