name: Contracts CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "packages/sports-manager-contracts/**"
    branches:
      - "**"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install build-essential
        run: |
          sudo apt-get install -y build-essential
          rm yarn.lock
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn 
      - run: yarn build
      - name: Run contract tests
        run: |
          cd packages/sports-manager-contracts
          yarn test
      - name: Run contract coverage
        run: |
          cd packages/sports-manager-contracts
          yarn coverage
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
