name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Toolkit and Remove Lockfile
        run: |
          sudo apt-get install -y make build-essential libudev-dev
          rm yarn.lock
      - name: Install Yarn and Packages
        run: |
          npm install -g yarn
          yarn install
      - name: Build Monorepo
        run: yarn build:ci
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
